### ISSUE TITLE
error[E0599]: no function or associated item named `insert_types` found for struct `anchor_spl::token_interface::Mint` in the current scope

### ISSUE THREAD

**Issue by 0xapp123** [raydium-io/raydium-cpi-example#15]
```
error[E0599]: no function or associated item named `insert_types` found for struct `anchor_spl::token_interface::Mint` in the current scope
    --> /root/.cargo/git/checkouts/raydium-cpi-81b7b026351bbf44/f16b5ea/programs/clmm-cpi/src/context.rs:1097:10
     |
1097 | #[derive(Accounts)]
     |          ^^^^^^^^ function or associated item not found in `anchor_spl::token_interface::Mint`
     |
     = note: this error originates in the derive macro `Accounts` (in Nightly builds, run with -Z macro-backtrace for more info)
```
How can I fix it?

**Comment by MetaverseMan** [comment]
Have you already fixed it? I am facing the same issue

**Comment by 0xapp123** [comment]
If you use the correct anchor version for this, it will be fixed.

**Comment by MetaverseMan** [comment]
> If you use the correct anchor version for this, it will be fixed.

I found another way to fix this,and it works well on anchor-0.31.1


```
# Source - https://stackoverflow.com/questions/78362485/anchor-shows-errors-no-associated-item-named-anchor-private-gen-idl-type-fo
# Posted by dev4all.sol
# Retrieved 2025-11-06, License - CC BY-SA 4.0
idl-build = ["anchor-lang/idl-build","anchor-spl/idl-build"]
```
